stages:
  - build

Build:
  stage: build
  image: rust
  cache:
    key: global
    paths:
      - target
  script:
    - cargo build --verbose
    - (apt update && apt install -y fortunes) > /dev/null
    - ./target/debug/fortune-rs
