[package]
name = "fortune-rs"
version = "0.1.0"
authors = ["Daan Boerlage <d@boerlage.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
clap = "2.33.0"
regex = "1.3.1"
