---
name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v3

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Lint
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy -- -Dwarnings

      - name: Build
        run: cargo build
